CREATE TABLE mail_log (
	id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	created DATETIME NOT NULL,
	last_updated DATETIME NOT NULL,
	from_email VARCHAR(256) NOT NULL,
	to_email VARCHAR(256) NOT NULL,
	subject VARCHAR(256) NOT NULL,
	message VARCHAR(1024) NOT NULL,
	api_key_id BIGINT NOT NULL
);

ALTER TABLE mail_log
	ADD FOREIGN KEY (api_key_id) REFERENCES api_key(id) ON UPDATE CASCADE ON DELETE RESTRICT;